name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 12 * * 1,4'
  workflow_dispatch:

jobs:
  ping-streamlit:
    runs-on: ubuntu-latest
    steps:
      - name: Visit Streamlit app
        run: curl -s "https://e-commerce-analytics-olist.streamlit.app/" > /dev/null